### PR TITLE
fixed size calculation in array scalar set etc

### LINKED ISSUE #2332: Check if multidim array size calculations are correct for tabmax, tabmin and tabsum
According to this coderabbitai review https://github.com/csound/csound/pull/2213#discussion_r2462811183 big if true if we are calculating the multidimensional array sizes incorrectly. We should be able to verify this claim by testing it in csd. I'd suggest testing it, if true, make a failing regression test in command line tests (or add it as a case to existing one).

### PR DESCRIPTION
**Pull request by vlazzarini**
Fix for #2332 - scalarset

### CODE REVIEW

**Comment by vlazzarini** [comment]
and tabmin, tabmax, tabsum

**Review by hlolli — APPROVED** [review]
nice!

File: OOps/array_ops.c [hunk 1]
```diff
@@ -2772,13 +2772,13 @@ int32_t tabqset1(CSOUND *csound, TABQUERY1 *p)
 int32_t tabmax(CSOUND *csound, TABQUERY *p)
 {
   ARRAYDAT *t = p->tab;
-  int32_t i, size = 0, pos = 0;;
+  int32_t i, size = t->sizes[0], pos = 0;;
```
Comment (hlolli) [inline OOps/array_ops.c:2775]: nit-pick: double semicolon needed?

Comment (vlazzarini) [reply OOps/array_ops.c:2775]: yep not needed. was it there before?
