### PR TITLE
fix for named instr ramps

### LINKED ISSUE #2201: Score ramps don't work with named instruments
I'm not sure if this is a bug or another "feature" but

```
<CsoundSynthesizer>
<CsOptions>
-odac -m134
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 64
nchnls = 2
0dbfs = 1

instr 1
	printf_i "p4 => %f\n", 1, p4
endin

instr meh
	printf_i "p4 => %f\n", 1, p4
endin

</CsInstruments>
<CsScore>
i1 0 0.1 42
i1 + 0.1 <
i1 + 0.1 44

i "meh" 1 0.1 42
i "meh" + 0.1 <
i "meh" + 0.1 44

</CsScore>
</CsoundSynthesizer>
```

prints

```
new alloc for instr 1:
p4 => 42.000000
p4 => 43.000000
p4 => 44.000000
new alloc for instr meh:
p4 => 42.000000
p4 => 0.000000
p4 => 44.000000
```

https://csound.com/docs/manual/ScoreRamping.html doesn't say that they don't work with named instuments, but just that it has to be "the same instrument".

### PR DESCRIPTION
**Pull request by vlazzarini**
closes #2201

### CODE REVIEW

File: Engine/swritestr.c [hunk 1]
```diff
@@ -225,24 +225,37 @@ static char *pfout(CSOUND *csound, SRTBLK *bp, char *p,
...
-
-    p1 = bp->p1val;
+{
+  MYFLT p1;
+  p1 = bp->p1val;
+  if(!IsStringCode(p1)) {
     while ((bp = bp->prvblk) != NULL
            && (bp->p1val != p1 || bp->text[0] != 'i'))
       ;
+   } else { // if str use insno as p1val is nan
```
Comment (kunstmusik) [inline Engine/swritestr.c:250]: Not sure what "is nan" is meaning here?

Comment (vlazzarini) [reply Engine/swritestr.c:250]: when p1 is given as a string, p1val can't be used because it is set to a NaN. The instr name is not available here in the structure data, but the instrument number is.

**Review by kunstmusik — APPROVED** [review]
I added the test CSD from the original issue and updated it to use asserts. Tests look good, approving and merging now.
